remote_theme: just-the-docs/just-the-docs
title: incitron docs
author: iain fullelove
description: incitron engine documentation for users and developers

url: "https://docs.incitron.com"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links for the upper right navigation
aux_links:
  "Code Repo":
    - "//github.com/incitron/incitron"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

markdown: kramdown